Repository Kelompok-12-Capstone/sociops-admin, pull requests merged in 2023-06, with the labels that each got.

#30 Feat: Get all list news dan fix get user info
  package.json
  src/app/news/list-news/page.jsx
  src/components/atoms/Button/Button/Button.atom.jsx
  src/components/atoms/TableV2/TableV2Row.atom.jsx
  src/config/redux/user/userThunk.jsx
  tailwind.config.js
Labels: feature

#31 feat: detail news logic
  jsconfig.json
  src/app/news/[id]/page.jsx
  src/app/news/detail-news/page.jsx
  src/app/news/list-news/page.jsx
  src/components/organisms/News/DetailNews/DetailNews.organism.jsx
  src/components/organisms/News/DetailNews/DetailNews.organismModel.jsx
  src/components/organisms/index.jsx
  src/config/redux/news/newsSelector.jsx
  src/config/redux/news/newsSlice.jsx
  src/config/redux/news/newsThunk.jsx
  src/config/redux/reducers/reducer.jsx
  src/config/redux/store/store.jsx
Labels: feature

#35 feat: menambahkan fitur statistic
  package.json
  src/app/customer/page.js
  src/app/dashboard/Dashboard.style.css
  src/app/dashboard/page.js
  src/app/fundraising/page.js
  src/app/volunteer/page.js
  src/components/organisms/FakeStatistic/FakeStatistic.organism.jsx
  src/components/organisms/Statistic/Statistic.organism.jsx
  src/components/organisms/Statistic/useStatistic.organismModel.jsx
  src/components/organisms/index.jsx
  src/config/redux/reducers/reducer.jsx
  src/config/redux/statistic/statisticSelector.jsx
  src/config/redux/statistic/statisticSlice.jsx
  src/config/redux/statistic/statisticThunk.jsx
Labels: feature

#36 fix feat create news post data
  src/app/news/create-news/page.jsx
  src/config/redux/news/newsThunk.jsx
Labels: feature

#38 fix: bug di react paginate
  src/app/news/list-news/page.jsx
Labels: bug

#39 connecting to the API for pengajuan program page's on the volunteer …
  src/app/fundraising/[id]/page.jsx
  src/app/fundraising/pengajuan-program/page.jsx
  src/app/volunteer/[id]/page.jsx
  src/app/volunteer/pengajuan-program/page.jsx
  src/components/organisms/Volunteer/DetailVolunteer/DetailVolunteer.organism.jsx
  src/components/organisms/Volunteer/DetailVolunteer/DetailVolunteer.organismModel.jsx
  src/components/organisms/index.jsx
  src/config/redux/reducers/reducer.jsx
  src/config/redux/store/store.jsx
  src/config/redux/volunteer/volunteerSelector.jsx
  src/config/redux/volunteer/volunteerSlice.jsx
  src/config/redux/volunteer/volunteerThunk.jsx
Labels: feature

#41 Connecting to the API for list program on volunteer and fundraising
  src/app/fundraising/list-program/page.jsx
  src/app/volunteer/list-program/page.jsx
Labels: feature

#42 connecting to the API for detail program page's on the volunteer
  src/components/organisms/News/DetailNews/DetailNews.organism.jsx
  src/components/organisms/News/DetailNews/DetailNews.organismModel.jsx
  src/components/organisms/Volunteer/DetailVolunteer/DetailVolunteer.organism.jsx
  src/components/organisms/Volunteer/DetailVolunteer/DetailVolunteer.organismModel.jsx
  src/config/redux/volunteer/volunteerSlice.jsx
Labels: feature

#43 fix alternative path on sidebar navigation
  src/app/fundraising/page.js
  src/components/molecules/Sidebar/SidebarNavigation.molecule.jsx
Labels: enhancement

#45 fix: header greeting text, foto profil user dan menambahkan scroll pada button navigation dashboard
  src/app/dashboard/page.js
  src/components/atoms/Header/HeaderGreetingText.atom.jsx
  src/components/molecules/Header/HeaderNotificationDropdown.molecule.jsx
Labels: enhancement

#46 feat: integrasi dengan API pada komponen program terbaru halaman dashboard fundraising dan set global moment js menjadi bahasa indonesia
  src/app/fundraising/page.js
  src/app/volunteer/page.js
  src/components/template/DefaultTemplate/DefaultTemplate.template.jsx
Labels: enhancement

#47 fix: refactoring code all pages, add folder views, and fix image on list news page
  src/app/customer/daftar-akun-pengguna/page.jsx
  src/app/customer/detail-permintaan-komunitas/page.jsx
  src/app/customer/page.js
  src/app/customer/pengguna-fundraising/page.jsx
  src/app/customer/pengguna-volunteer/page.jsx
  src/app/customer/permintaan-komunitas/page.jsx
  src/app/dashboard/page.js
  src/app/fundraising/[id]/page.jsx
  src/app/fundraising/list-program/page.jsx
  src/app/fundraising/page.js
  src/app/fundraising/pengajuan-program/page.jsx
  src/app/fundraising/riwayat-program/page.jsx
  src/app/fundraising/transaksi/page.jsx
  src/app/news/[id]/page.jsx
  src/app/news/create-news/page.jsx
  src/app/news/list-news/page.jsx
  src/app/news/page.js
  src/app/volunteer/[id]/page.jsx
  src/app/volunteer/list-program/page.jsx
  src/app/volunteer/page.js
  src/app/volunteer/pengajuan-program/page.jsx
  src/app/volunteer/riwayat-program/page.jsx
  src/components/atoms/TableV2/TableV2Row.atom.jsx
  src/components/views/Customer/DaftarAkunPengguna/DaftarAkunPengguna.view.jsx
  src/components/views/Customer/DashboardCustomer.view.jsx
  src/components/views/Customer/DetailPermintaanKomunitas/DetailPermintaanKomunitas.view.jsx
  src/components/views/Customer/PenggunaFundraising/PenggunaFundraising.view.jsx
  src/components/views/Customer/PenggunaVolunteer/PenggunaVolunteer.view.jsx
  src/components/views/Customer/PermintaanKomunitas/PermintaanKomunitas.view.jsx
  src/components/views/Dashboard/Dashboard.view.jsx
  src/components/views/Fundraising/DashboardFundraising.view.jsx
  src/components/views/Fundraising/DetailProgramFundraising/DetailProgramFundraising.view.jsx
  src/components/views/Fundraising/ListProgramFundraising/ListProgramFundraising.view.jsx
  src/components/views/Fundraising/PengajuanProgramFundraising/PengajuanProgramFundraising.view.jsx
  src/components/views/Fundraising/RiwayatProgramFundraising/RiwayatProgramFundraising.view.jsx
  src/components/views/Fundraising/Transaksi/Transaksi.view.jsx
  src/components/views/News/CreateNews/CreateNews.view.jsx
  src/components/views/News/DashboardNews.view.jsx
  src/components/views/News/ListNews/ListNews.view.jsx
  src/components/views/Volunteer/DashboardVolunteer.view.jsx
  src/components/views/Volunteer/ListProgramVolunteer/ListProgramVolunteer.view.jsx
  src/components/views/Volunteer/PengajuanProgramVolunteer/PengajuanProgramVolunteer.view.jsx
  src/components/views/Volunteer/RiwayatProgramVolunteer/RiwayatProgramVolunteer.view.jsx
  src/components/views/index.js
Labels: enhancement

#52 Create Feat Detail Fundraising
  src/app/fundraising/[id]/page.jsx
  src/components/organisms/Fundraising/DetailFundraising/DetailFundraising.organism.jsx
  src/components/organisms/Fundraising/DetailFundraising/DetailFundraising.organismModel.jsx
  src/config/redux/fundraising/fundraisingSelector.jsx
  src/config/redux/fundraising/fundraisingSlice.jsx
  src/config/redux/fundraising/fundraisingThunk.jsx
Labels: feature

#58 feat mengintegrasikan API pada pengguna voluenteer
  src/components/views/Customer/PenggunaVolunteer/PenggunaVolunteer.view.jsx
  src/config/redux/user/userSelector.jsx
  src/config/redux/user/userSlice.jsx
  src/config/redux/user/userThunk.jsx
Labels: feature

#59 Integration API to Pengguna Fundraising
  src/components/views/Customer/PenggunaFundraising/PenggunaFundraising.view.jsx
  src/components/views/Customer/PenggunaVolunteer/PenggunaVolunteer.view.jsx
  src/config/redux/user/userSelector.jsx
  src/config/redux/user/userSlice.jsx
  src/config/redux/user/userThunk.jsx
Labels: feature

#64 enhancement feature
  src/components/atoms/Header/HeaderSearchInput.atom.jsx
  src/components/molecules/Header/HeaderNotificationDropdown.molecule.jsx
  src/components/organisms/Fundraising/DetailFundraising/DetailFundraising.organism.jsx
  src/components/views/Customer/DaftarAkunPengguna/DaftarAkunPengguna.view.jsx
  src/components/views/Customer/PenggunaFundraising/PenggunaFundraising.view.jsx
  src/components/views/Customer/PenggunaVolunteer/PenggunaVolunteer.view.jsx
Labels: enhancement

#66 Sociops v1.5
  src/components/views/News/CreateNews/CreateNews.view.jsx
Labels: bug

#68 enhancement login feature
  src/components/atoms/Input/InputText/InputText.atom.jsx
  src/components/organisms/Home/FormSignIn/FormSignIn.organism.jsx
  src/components/organisms/Home/FormSignIn/FormSignIn.organismModel.jsx
Labels: enhancement
